declare global {
    interface ImportMeta {
        readonly env: {
            readonly VITE_GEMINI_API_KEY: string;
        };
    }
}

import { GoogleGenAI, Modality } from "@google/genai";
import { SelectedProductInfo, AiModel } from '../types';

const stripBase64Prefix = (base64: string): string => {
    return base64.split(',')[1] || base64;
};

// GEMINI API SERVICE
const createGeminiPrompt = (productInfos: SelectedProductInfo[]): string => {
    if (productInfos.length === 0) return "Do not change the image.";

    const createIndividualPrompt = (info: SelectedProductInfo): string => {
        const item = info.product.name;
        if (info.product.isCustom) return `Add custom item: ${item}`;
        switch (info.subCategory.toLowerCase()) {
            case 'lipstick': return `apply ${item} lipstick`;
            case 'eyeliner': return `apply ${item} eyeliner`;
            case 'eye shadow': return `apply ${item} eye shadow`;
            case 'foundation': return `apply ${item} foundation`;
            case 'sunglasses': return `put on ${item} sunglasses`;
            case 'glasses': return `put on ${item}`;
            case 'hair accessories': return `add a ${item} to the hair`;
            case 'shirts/tops': case 'dresses': case 'jackets': return `change clothing to ${item}`;
            default: return `apply a ${item}`;
        }
    };
    
    if (productInfos.length === 1) {
        return `Realistically ${createIndividualPrompt(productInfos[0])} on the person. Ensure the result is high-quality and blends seamlessly. Do not change anything else in the image.`;
    }

    const instructions = productInfos.map(info => `- ${createIndividualPrompt(info)}`).join('\n');
    return `Apply the following changes to the person in the image, ensuring they all blend together realistically and cohesively:\n${instructions}\n\nDo not change the background or any other features. The final result should be a single, high-quality image.`;
};

const generateWithGemini = async (
    base64Image: string,
    mimeType: string,
    productInfos: SelectedProductInfo[]
): Promise<string> => {
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (!apiKey) throw new Error("VITE_GEMINI_API_KEY is not set in .env file.");

    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { inlineData: { data: stripBase64Prefix(base64Image), mimeType } },
                { text: createGeminiPrompt(productInfos) },
            ],
        },
        config: { responseModalities: [Modality.IMAGE, Modality.TEXT] },
    });
    
    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    throw new Error("No image was generated by Gemini. The AI may have refused the request.");
};

// POLLINATIONS.AI SERVICE - Optimized for speed
const uploadImageToPublicHost = async (base64Image: string): Promise<string> => {
    const base64Data = stripBase64Prefix(base64Image);
    const blob = await fetch(`data:image/jpeg;base64,${base64Data}`).then(r => r.blob());
    
    // Race all upload services in parallel for fastest response
    const uploadPromises = [
        // tmpfiles.org
        (async () => {
            const formData = new FormData();
            formData.append('file', blob, 'image.jpg');
            const response = await fetch('https://tmpfiles.org/api/v1/upload', {
                method: 'POST',
                body: formData,
                headers: { 'Accept': 'application/json' }
            });
            if (response.ok) {
                const data = await response.json();
                if (data.status === 'success' && data.data?.url) {
                    const originalUrl = data.data.url;
                    if (originalUrl.includes('tmpfiles.org/') && !originalUrl.includes('/dl/')) {
                        const urlParts = originalUrl.split('/');
                        if (urlParts.length >= 4) {
                            return `https://tmpfiles.org/dl/${urlParts[3]}/${urlParts[4] || 'image.jpg'}`;
                        }
                    }
                    return originalUrl;
                }
            }
            throw new Error('tmpfiles failed');
        })(),
        
        // 0x0.st
        (async () => {
            const formData = new FormData();
            formData.append('file', blob, 'image.jpg');
            const response = await fetch('https://0x0.st', { method: 'POST', body: formData });
            if (response.ok) {
                const url = await response.text();
                if (url && url.trim().startsWith('https://')) return url.trim();
            }
            throw new Error('0x0.st failed');
        })(),
        
        // catbox.moe
        (async () => {
            const formData = new FormData();
            formData.append('fileToUpload', blob, 'image.jpg');
            formData.append('reqtype', 'fileupload');
            const response = await fetch('https://catbox.moe/user/api.php', { method: 'POST', body: formData });
            if (response.ok) {
                const url = await response.text();
                if (url && url.trim().startsWith('https://')) return url.trim();
            }
            throw new Error('catbox failed');
        })()
    ];
    
    // Return the first successful upload
    try {
        return await Promise.any(uploadPromises);
    } catch {
        throw new Error('Failed to upload image. All hosting services are unavailable.');
    }
};

const generateRandomSeed = (): number => {
    return Math.floor(Math.random() * 2147483647);
};

const generateWithPollinations = async (
    pollinationsModel: string,
    base64Image: string,
    productInfos: SelectedProductInfo[]
): Promise<string> => {
    // Upload user image and build prompt in parallel for speed
    const [userImageUrl, promptParts] = await Promise.all([
        uploadImageToPublicHost(base64Image),
        Promise.resolve(productInfos.map(info => {
            const productName = info.product.name;
            const category = info.subCategory.toLowerCase();
            
            switch (category) {
                case 'lipstick': return `${productName} lipstick on lips`;
                case 'eyeliner': return `${productName} eyeliner on eyes`;
                case 'eye shadow': return `${productName} eyeshadow on eyelids`;
                case 'foundation': return `${productName} foundation on face`;
                case 'sunglasses': return `wearing ${productName} sunglasses`;
                case 'glasses': return `wearing ${productName} glasses`;
                case 'hair accessories': return `${productName} in hair`;
                case 'shirts/tops': return `wearing ${productName} shirt`;
                case 'dresses': return `wearing ${productName} dress`;
                case 'jackets': return `wearing ${productName} jacket`;
                default: return `${productName}`;
            }
        }))
    ]);
    
    // Build prompt and collect product image URLs
    const prompt = `person, ${promptParts.join(', ')}`;
    const productImageUrls = productInfos
        .map(p => p.product.imageUrl)
        .filter((url): url is string => !!url && url.startsWith('http'));

    // Build final URL efficiently
    const seed = generateRandomSeed();
    const imageParam = [...productImageUrls, userImageUrl].join(',');
    
    return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?model=${pollinationsModel}&private=true&nofeed=true&nologo=true&width=1024&height=1024&seed=${seed}&image=${imageParam}`;
};

// MAIN API ROUTER
export const generateTryOnImage = async (
    model: AiModel,
    base64Image: string,
    mimeType: string,
    productInfos: SelectedProductInfo[]
): Promise<string> => {
    const pollinationsModel = model.startsWith('pollinations') ? model.split('-')[1] : 'kontext';
    return generateWithPollinations(pollinationsModel, base64Image, productInfos);
};